maxidom:
    shop: 'maxidom'
    source: 'https'
    fields:
        name:
            js_var: 'vueImpression' #сюда имя пременной для построения регулярки
            js_name: 'name'
            css: '[itemprop="name"]'
        reg_price:
            js_var: 'vueImpression' #сюда имя пременной для построения регулярки
            js_name: 'price_old'
            css: '[l1__product-body-buy-price-discount-old span]'
        price:
            js_var: 'vueImpression' #сюда имя пременной для построения регулярки
            js_name: 'price'
            css: '[itemprop="price"]'
        brand:
            js_var: 'vueImpression' #сюда имя пременной для построения регулярки
            js_name: 'brand'
            css:
        sku:
            js_var: 'vueImpression' #сюда имя пременной для построения регулярки
            js_name: 'sku'
            css:
    cookies:
        MAXI_LOC_ID: '2'

    urls_path: 'D:\ETL\ETL_pipline\my_parser\sources\URLs.xlsx'
    max_workers: 3
ozon:
    shop: 'ozon'
    source: 'browser'
    fields:
        name:
            css: 'h1.tsHeadline550Medium'
        reg_price:
            css: '[data-widget="webPrice"] > div > div:nth-child(2) .tsBody400Small'
        price:
            css: '[data-widget="webPrice"] .tsHeadline500Medium'
#        brand:
#            css:
#        sku:
#            css:
#    cookies:
    urls_path: 'D:\ETL\ETL_pipline\my_parser\sources\URLs.xlsx'
    max_workers: 3
